// GlobeClouds — weather at a real altitude, that you fly through.
//
// Geoff: "ideally it's like real clouds at scale so we can be above or below them, and they slowly
// move... but maybe I'm hoping for too much!"
//
// Not too much — but worth being precise about what is and is not affordable, because the honest
// version of this is a trade.
//
// TRUE VOLUMETRIC CLOUDS raymarch a 3D noise field: forty to a hundred samples per pixel, per
// frame. They are what modern flight sims use and they are magnificent. They would also cost more
// than everything else in this scene put together — two hundred skinned soldiers, four Kaiju,
// a thousand fire particles and a streaming planet — and this runs in a browser at dpr 1.
//
// WHAT THIS IS INSTEAD is a real SHELL at a real altitude: a sphere at 2 km, with the cloud shapes
// generated by fractal noise in the fragment shader and drifting slowly. The part Geoff actually
// asked for falls straight out of that — it is a genuine surface at a genuine height, so flying up
// through it puts you above it, and the transition is real rather than faked.
//
// TWO SHELLS, not one. A single shell is unmistakably a painted ceiling the moment you move,
// because everything in it slides at exactly one rate. Two at different heights, drifting at
// different speeds, give parallax — and parallax is most of what the eye uses to judge that
// something has depth. It is the same trick a matte painter uses, and it costs one extra draw.
//
// THE PLANET IS A SPHERE, which does the rest for free: the shell curves away, so clouds genuinely
// meet the horizon and there is no edge to the sky.

import { useEffect, useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { PLANET_RADIUS, METRES_PER_UNIT } from './cubeSphere';
import { sunDirection } from './GlobeLighting';

/** Cloud base and the second deck, in metres. Real cumulus sits about here. */
const DECK_LOW_M = 1900;
const DECK_HIGH_M = 3100;

/**
 * How much of the sky is covered, 0 to 1.
 *
 * 0.42 is a scattered-to-broken day: enough to break the light up and give the sky something to be,
 * far short of overcast — which would kill the sun that the rest of this work exists to show off.
 */
const COVERAGE = 0.42;

/** Metres per repeat of the largest cloud feature. Cumulus systems run tens of kilometres. */
const CLOUD_SCALE_M = 42000;

const CLOUD_VERT = /* glsl */`
  varying vec3 vWorld;
  varying vec3 vNrm;
  void main() {
    vec4 wp = modelMatrix * vec4(position, 1.0);
    vWorld = wp.xyz;
    vNrm = normalize(mat3(modelMatrix) * normal);
    gl_Position = projectionMatrix * viewMatrix * wp;
  }
`;

const CLOUD_FRAG = /* glsl */`
  uniform float uTime;
  uniform float uCoverage;
  uniform float uScale;
  uniform vec3  uSunDir;
  uniform vec3  uSunCol;
  uniform vec3  uSkyCol;
  uniform float uDrift;
  uniform float uOpacity;
  varying vec3 vWorld;
  varying vec3 vNrm;

  float cHash(vec3 p) {
    p = fract(p * 0.3183099 + vec3(0.71, 0.113, 0.419));
    p *= 17.0;
    return fract(p.x * p.y * p.z * (p.x + p.y + p.z));
  }
  float cNoise(vec3 x) {
    vec3 i = floor(x); vec3 f = fract(x);
    f = f * f * (3.0 - 2.0 * f);
    return mix(mix(mix(cHash(i + vec3(0,0,0)), cHash(i + vec3(1,0,0)), f.x),
                   mix(cHash(i + vec3(0,1,0)), cHash(i + vec3(1,1,0)), f.x), f.y),
               mix(mix(cHash(i + vec3(0,0,1)), cHash(i + vec3(1,0,1)), f.x),
                   mix(cHash(i + vec3(0,1,1)), cHash(i + vec3(1,1,1)), f.x), f.y), f.z);
  }
  float cFbm(vec3 p) {
    float s = 0.0, a = 0.5;
    for (int i = 0; i < 5; i++) { s += a * cNoise(p); p = p * 2.07 + 11.3; a *= 0.5; }
    return s;
  }

  void main() {
    // Sample in the shell's own direction from the planet centre, so the pattern lives ON the
    // sphere and never stretches at a pole the way a lat/long projection does.
    vec3 dir = normalize(vWorld);
    vec3 p = dir * uScale;
    // DRIFT. Two layers moving at different rates: the shapes themselves crawl, and a finer field
    // slides across them faster, which is what makes clouds boil rather than merely slide.
    vec3 flow = vec3(uTime * uDrift, uTime * uDrift * 0.41, -uTime * uDrift * 0.23);
    float base = cFbm(p + flow);
    float detail = cFbm(p * 3.7 + flow * 2.6);
    float d = base * 0.72 + detail * 0.28;

    // COVERAGE AS A THRESHOLD, not a multiply. Clouds have edges and gaps of clear sky between
    // them; scaling a noise field down just makes uniform haze everywhere.
    float cover = smoothstep(1.0 - uCoverage, 1.0 - uCoverage + 0.30, d);
    if (cover <= 0.003) discard;

    // LIGHTING. A cloud is lit from the sun side and grey-blue on the other, and the thin edges
    // glow because light passes through them, which is the detail that sells it. The noise value
    // doubles as thickness: high is the dense middle, low is the wispy rim.
    float sunAmt = clamp(dot(normalize(vNrm), uSunDir) * 0.5 + 0.5, 0.0, 1.0);
    float thickness = smoothstep(0.0, 0.55, cover);
    vec3 lit = mix(uSkyCol, uSunCol, sunAmt);
    // Silver lining: the thinner the cloud the more sun comes through it.
    vec3 col = mix(lit * 1.25, lit * 0.66, thickness);

    // Fade out at grazing angles. Looking along the shell you would otherwise see through
    // kilometres of a surface with no thickness, which reads as a hard painted edge.
    float graze = abs(dot(normalize(vNrm), normalize(vWorld - cameraPosition)));
    float edge = smoothstep(0.02, 0.35, graze);

    gl_FragColor = vec4(col, cover * uOpacity * edge);
  }
`;

function Deck({ altitudeM, drift, opacity, coverage }: {
  altitudeM: number; drift: number; opacity: number; coverage: number;
}) {
  const mat = useMemo(() => new THREE.ShaderMaterial({
    uniforms: {
      uTime: { value: 0 },
      uCoverage: { value: coverage },
      uScale: { value: (PLANET_RADIUS * METRES_PER_UNIT) / CLOUD_SCALE_M },
      uSunDir: { value: new THREE.Vector3(0, 1, 0) },
      uSunCol: { value: new THREE.Color(0xfff0dc) },
      uSkyCol: { value: new THREE.Color(0x8ea9c8) },
      uDrift: { value: drift },
      uOpacity: { value: opacity },
    },
    vertexShader: CLOUD_VERT,
    fragmentShader: CLOUD_FRAG,
    transparent: true,
    depthWrite: false,
    // BOTH SIDES, and this is the whole "above or below" requirement: from underneath you see the
    // shell's inside, from above its outside. Single-sided, the clouds would vanish the instant you
    // climbed through them.
    side: THREE.DoubleSide,
    fog: false,
  }), [coverage, drift, opacity]);
  useEffect(() => () => mat.dispose(), [mat]);

  useFrame((state) => {
    mat.uniforms.uTime.value = state.clock.elapsedTime;
    // Lit by the SAME sun as the ground, so the decks warm up and the shadow sides go blue in step
    // with everything below them.
    mat.uniforms.uSunDir.value.copy(sunDirection);
  });

  const r = PLANET_RADIUS + altitudeM / METRES_PER_UNIT;
  // 96 segments: the shell only ever needs to be smooth in silhouette, and all the shape is in the
  // shader. More geometry would buy nothing.
  return (
    <mesh material={mat} frustumCulled={false} renderOrder={-5}>
      <sphereGeometry args={[r, 96, 64]} />
    </mesh>
  );
}

export function GlobeClouds() {
  return (
    <>
      {/* The lower deck is denser and slower; the upper is thin, faster and more broken, which is
          how a real sky is layered. */}
      <Deck altitudeM={DECK_LOW_M} drift={0.0022} opacity={0.85} coverage={COVERAGE} />
      <Deck altitudeM={DECK_HIGH_M} drift={0.0051} opacity={0.45} coverage={COVERAGE * 0.72} />
    </>
  );
}
