-- Step 1: Update all mystery block keys to temporary values
UPDATE blocks SET key = 'temp_mystery_2' WHERE class = 'mystery' AND tier = 2;
UPDATE blocks SET key = 'temp_mystery_3' WHERE class = 'mystery' AND tier = 3;
UPDATE blocks SET key = 'temp_mystery_4' WHERE class = 'mystery' AND tier = 4;
UPDATE blocks SET key = 'temp_mystery_5' WHERE class = 'mystery' AND tier = 5;
UPDATE blocks SET key = 'temp_mystery_6' WHERE class = 'mystery' AND tier = 6;
UPDATE blocks SET key = 'temp_mystery_7' WHERE class = 'mystery' AND tier = 7;
UPDATE blocks SET key = 'temp_mystery_8' WHERE class = 'mystery' AND tier = 8;
UPDATE blocks SET key = 'temp_mystery_9' WHERE class = 'mystery' AND tier = 9;
UPDATE blocks SET key = 'temp_mystery_10' WHERE class = 'mystery' AND tier = 10;
UPDATE blocks SET key = 'temp_mystery_11' WHERE class = 'mystery' AND tier = 11;
UPDATE blocks SET key = 'temp_mystery_12' WHERE class = 'mystery' AND tier = 12;
UPDATE blocks SET key = 'temp_mystery_13' WHERE class = 'mystery' AND tier = 13;
UPDATE blocks SET key = 'temp_mystery_14' WHERE class = 'mystery' AND tier = 14;
UPDATE blocks SET key = 'temp_mystery_15' WHERE class = 'mystery' AND tier = 15;
UPDATE blocks SET key = 'temp_mystery_16' WHERE class = 'mystery' AND tier = 16;
UPDATE blocks SET key = 'temp_mystery_17' WHERE class = 'mystery' AND tier = 17;
UPDATE blocks SET key = 'temp_mystery_18' WHERE class = 'mystery' AND tier = 18;
UPDATE blocks SET key = 'temp_mystery_19' WHERE class = 'mystery' AND tier = 19;
UPDATE blocks SET key = 'temp_mystery_20' WHERE class = 'mystery' AND tier = 20;
UPDATE blocks SET key = 'temp_mystery_21' WHERE class = 'mystery' AND tier = 21;
UPDATE blocks SET key = 'temp_mystery_22' WHERE class = 'mystery' AND tier = 22;
UPDATE blocks SET key = 'temp_mystery_23' WHERE class = 'mystery' AND tier = 23;
UPDATE blocks SET key = 'temp_mystery_24' WHERE class = 'mystery' AND tier = 24;
UPDATE blocks SET key = 'temp_mystery_25' WHERE class = 'mystery' AND tier = 25;
UPDATE blocks SET key = 'temp_mystery_26' WHERE class = 'mystery' AND tier = 26;
UPDATE blocks SET key = 'temp_mystery_27' WHERE class = 'mystery' AND tier = 27;
UPDATE blocks SET key = 'temp_mystery_28' WHERE class = 'mystery' AND tier = 28;
UPDATE blocks SET key = 'temp_mystery_29' WHERE class = 'mystery' AND tier = 29;
UPDATE blocks SET key = 'temp_mystery_30' WHERE class = 'mystery' AND tier = 30;

-- Step 2: Update from temporary to final keys
UPDATE blocks SET key = 'mystery_2' WHERE key = 'temp_mystery_2';
UPDATE blocks SET key = 'mystery_3' WHERE key = 'temp_mystery_3';
UPDATE blocks SET key = 'mystery_4' WHERE key = 'temp_mystery_4';
UPDATE blocks SET key = 'mystery_5' WHERE key = 'temp_mystery_5';
UPDATE blocks SET key = 'mystery_6' WHERE key = 'temp_mystery_6';
UPDATE blocks SET key = 'mystery_7' WHERE key = 'temp_mystery_7';
UPDATE blocks SET key = 'mystery_8' WHERE key = 'temp_mystery_8';
UPDATE blocks SET key = 'mystery_9' WHERE key = 'temp_mystery_9';
UPDATE blocks SET key = 'mystery_10' WHERE key = 'temp_mystery_10';
UPDATE blocks SET key = 'mystery_11' WHERE key = 'temp_mystery_11';
UPDATE blocks SET key = 'mystery_12' WHERE key = 'temp_mystery_12';
UPDATE blocks SET key = 'mystery_13' WHERE key = 'temp_mystery_13';
UPDATE blocks SET key = 'mystery_14' WHERE key = 'temp_mystery_14';
UPDATE blocks SET key = 'mystery_15' WHERE key = 'temp_mystery_15';
UPDATE blocks SET key = 'mystery_16' WHERE key = 'temp_mystery_16';
UPDATE blocks SET key = 'mystery_17' WHERE key = 'temp_mystery_17';
UPDATE blocks SET key = 'mystery_18' WHERE key = 'temp_mystery_18';
UPDATE blocks SET key = 'mystery_19' WHERE key = 'temp_mystery_19';
UPDATE blocks SET key = 'mystery_20' WHERE key = 'temp_mystery_20';
UPDATE blocks SET key = 'mystery_21' WHERE key = 'temp_mystery_21';
UPDATE blocks SET key = 'mystery_22' WHERE key = 'temp_mystery_22';
UPDATE blocks SET key = 'mystery_23' WHERE key = 'temp_mystery_23';
UPDATE blocks SET key = 'mystery_24' WHERE key = 'temp_mystery_24';
UPDATE blocks SET key = 'mystery_25' WHERE key = 'temp_mystery_25';
UPDATE blocks SET key = 'mystery_26' WHERE key = 'temp_mystery_26';
UPDATE blocks SET key = 'mystery_27' WHERE key = 'temp_mystery_27';
UPDATE blocks SET key = 'mystery_28' WHERE key = 'temp_mystery_28';
UPDATE blocks SET key = 'mystery_29' WHERE key = 'temp_mystery_29';
UPDATE blocks SET key = 'mystery_30' WHERE key = 'temp_mystery_30';